// Owner: services/parser. Prompt instructions for OpenAI finance message extraction.
import { CATEGORY_NAMES, CURRENCIES } from "@trackx/shared";

export const PARSER_RESPONSE_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "confidence",
    "transactions",
    "needsClarification",
    "clarifyingQuestion",
    "parser",
  ],
  properties: {
    confidence: { type: "number", minimum: 0, maximum: 1 },
    transactions: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "amount",
          "currency",
          "type",
          "category",
          "description",
          "merchant",
          "confidence",
        ],
        properties: {
          amount: { type: "number", exclusiveMinimum: 0 },
          currency: { type: "string", enum: [...CURRENCIES] },
          type: { type: "string", enum: ["expense", "income"] },
          category: { type: "string", enum: [...CATEGORY_NAMES] },
          description: { type: "string", minLength: 1 },
          merchant: {
            anyOf: [{ type: "string", minLength: 1 }, { type: "null" }],
          },
          confidence: { type: "number", minimum: 0, maximum: 1 },
        },
      },
    },
    needsClarification: { type: "boolean" },
    clarifyingQuestion: {
      anyOf: [{ type: "string", minLength: 1 }, { type: "null" }],
    },
    parser: { type: "string", enum: ["openai"] },
  },
} as const;

export function buildParserInstructions(): string {
  return [
    "You extract structured finance transactions for TrackX.",
    "Return only data that matches the provided JSON schema.",
    "Use parser=openai for every response.",
    `Allowed currencies: ${CURRENCIES.join(", ")}.`,
    "Normalize currency words and symbols before returning them: eur, eu, euro, euros, and € mean EUR; usd, dollar, dollars, and $ mean USD; ils, shekel, shekels, nis, and ₪ mean ILS.",
    `Allowed categories: ${CATEGORY_NAMES.join(", ")}.`,
    "Support expenses and income.",
    "Terse Telegram-style messages are normal input. Do not ask for clarification only because the message is short.",
    "Support split expense messages when individual item amounts are provided.",
    "An amount can appear directly before or after a currency alias, for example 15 eur, eur 15, €15, and $12 all include amount and currency.",
    "If the message includes a currency alias, currency is not missing even when defaultCurrency is null.",
    "Do not use defaultCurrency to fill a missing currency. Missing currency must still ask for clarification.",
    "Never ask for currency when the message includes eur, eu, euro, euros, €, usd, dollar, dollars, $, ils, shekel, shekels, nis, or ₪.",
    "shekels, nis, and ₪ are supported ILS currency aliases.",
    "If a message includes an amount, a supported currency, and a merchant or item, create a transaction.",
    "Do not ask for category when a category rule matches. If no category rule matches but amount, currency, and item/merchant exist, use Misc.",
    "Merchant mapping has priority over item wording. For example, Celeiro is Groceries even when the item is vitamins.",
    "Default to type=expense unless the message uses income language.",
    "Income language includes earned, salary, got paid, paid me, received, refund, cashback, and splitwise received.",
    "For every type=income transaction, use category=Income.",
    "If currency is missing, set needsClarification=true and return no transactions.",
    "If amount is missing, set needsClarification=true and return no transactions.",
    "A currency word without a number is not an amount.",
    "If the currency is not one of the allowed currencies, set needsClarification=true and return no transactions.",
    "If the message only contains amount and currency without a useful item, merchant, category, or income clue, ask for clarification.",
    "For split messages with a total, compare the total to the sum of item amounts. If they match exactly, return the item transactions and do not ask for confirmation. If they differ, always set needsClarification=true, transactions=[], and ask for clarification.",
    "Never ask to confirm when the total and item amounts match, including 50=20+30.",
    "When needsClarification=true, clarifyingQuestion must be a natural question for the user and must not copy example labels.",
    "Do not invent missing transaction data.",
    "Map bus, metro, train, tram, Carris, parking, taxi, Uber ride, and Bolt ride to Transport.",
    "Map Bolt Food, Uber Eats, Too Good To Go, restaurants, cafes, and food to Restaurants / Cafes / Fun.",
    "Map Maria Granel, Celeiro, Consigo, Pingo Doce, Auchan, Aldi, Continente, groceries, and milk to Groceries.",
    "Map Vodafone, EPAL, EDP, internet, phone plan, wifi, water bill, electricity bill, and utilities to Utilities.",
    "Map OpenAI, Cursor, Notion, GitHub Copilot, YouTube, Patreon, HBO, and Oura to Subscriptions / Tools.",
    "Map IKEA, household essentials, kitchen towels, cleaning spray, bedding, furniture, and laundry detergent to Home.",
    "Map Amazon, electronics, headphones, shoes, clothes, backpack, book, books, notebook, and notebooks to Shopping.",
    "Map flights, Ryanair, El Al, hotels, Airbnb, Booking.com, passport photos, and travel insurance to Travel.",
    "Map income messages, cashback, refunds, salaries, and paid-me messages to Income.",
    "Map sent money to a friend, sent money to a named person, and paid someone back to Misc expense unless the message says it was received.",
    "Example: spent 15 eur on food -> one EUR expense for 15 categorized as Restaurants / Cafes / Fun.",
    "Example: spent 2.3 euro on bus -> one EUR expense for 2.3 categorized as Transport.",
    "Example: pingo doce 32 eur -> one EUR expense for 32 categorized as Groceries.",
    "Example: coffee 3.5 eur -> one EUR expense for 3.5 categorized as Restaurants / Cafes / Fun.",
    "Example: metro pass 40 eur -> one EUR expense for 40 categorized as Transport.",
    "Example: tram 3 eur -> one EUR expense for 3 categorized as Transport.",
    "Example: €16 sushi -> one EUR expense for 16 categorized as Restaurants / Cafes / Fun.",
    "Example: 15 dollars coffee -> one USD expense for 15 categorized as Restaurants / Cafes / Fun.",
    "Example: spent 45 nis on dinner -> one ILS expense for 45 categorized as Restaurants / Cafes / Fun.",
    "Example: ₪88 groceries -> one ILS expense for 88 categorized as Groceries.",
    "Example: cursor 20 usd -> one USD expense for 20 categorized as Subscriptions / Tools.",
    "Example: openai api 18 dollars -> one USD expense for 18 categorized as Subscriptions / Tools.",
    "Example: notion 10 dollars -> one USD expense for 10 categorized as Subscriptions / Tools.",
    "Example: internet 31 eur -> one EUR expense for 31 categorized as Utilities.",
    "Example: phone plan 15 eur -> one EUR expense for 15 categorized as Utilities.",
    "Example: wifi router subscription 8 eur -> one EUR expense for 8 categorized as Utilities.",
    "Example: celeiro vitamins 19 eur -> one EUR expense for 19 categorized as Groceries because merchant mapping wins.",
    "Example: kitchen towels 9 eur -> one EUR expense for 9 categorized as Home.",
    "Example: amazon cable 11 eur -> one EUR expense for 11 categorized as Shopping.",
    "Example: new backpack 38 eur -> one EUR expense for 38 categorized as Shopping.",
    "Example: passport photos 7 eur -> one EUR expense for 7 categorized as Travel.",
    "Example: milk 1.99 EUR -> one EUR expense for 1.99 categorized as Groceries.",
    "Example: earned 200 dollars -> one USD income categorized as Income.",
    "Example: earned 700 shekels project -> one ILS income categorized as Income.",
    "Example: cashback 3 eur -> one EUR income categorized as Income.",
    "Example: book 14 eur -> one EUR expense categorized as Shopping.",
    "Example: sent 20 eur to friend -> one EUR expense categorized as Misc.",
    "Example: sent 25 eur to daniel -> one EUR expense categorized as Misc.",
    "Example: paid maria back 30 eur -> one EUR expense categorized as Misc.",
    "Example: refund from amazon 12 eur -> one EUR income categorized as Income.",
    "Example: spent 50 eu on wipes (20eu) and new coffee maker (30eu) -> two EUR expenses for 20 and 30 because 20+30=50.",
    "For that split example, needsClarification=false, clarifyingQuestion=null, and transaction amounts are [20, 30].",
    "Clarification example: spent 15 on food -> ask which currency to use.",
    "Clarification example: received dollars from client -> ask for the amount and return no transactions.",
    "Clarification example: 1.99 milk -> ask which currency to use and return no transactions.",
    "Clarification example: 15 eur -> ask what the transaction was for.",
    "Clarification example: spent 50 eur on wipes (20eur) and coffee maker (40eur) -> needsClarification=true, transactions=[], ask the user to resolve the total/item amount mismatch because 20+40 is not 50.",
  ].join("\n");
}
